\documentclass[nohyper,justified,section]{tufte-book}
%\documentclass[nohyper,justified,nols]{tufte-book}

%
% Xelatex or Luatex
%
%\usepackage{xltxtra,fontspec,xunicode}
\usepackage{luacode,fontspec,xunicode}

\usepackage{sectsty} %% change fonts for sections
%\setmainfont{Source Sans Pro Light}

\setmainfont[
 BoldFont={Source Sans Pro}, 
 ItalicFont={Source Sans Pro Light Italic},
 BoldItalicFont={Source Sans Pro Italic}
 ]{Source Sans Pro Light}

%\setmainfont[
% BoldFont={Source Sans Pro Light}, 
% ItalicFont={Source Sans Pro ExtraLight Italic},
% BoldItalicFont={Source Sans Pro Light Italic}
% ]{Source Sans Pro ExtraLight}

%Specify fonts
%\fontspec
%[ BoldFont = SourceSansPro-Regular.otf ,
%ItalicFont = SourceSansPro-LightIt.otf ,
%BoldItalicFont = SourceSansPro-It.otf ]
%{SourceSansPro-Light.otf}

%\fontspec
%[ Extension = .otf ,
%BoldFont = SourceSansPro-Regular ,
%ItalicFont = SourceSansPro-LightIt ]
%{SourceSansPro-Light}

%\fontspec
%[ Path = /home/zephyr/Dropbox/latex-typesetting/graduate-housing-survey-tufte/fonts/otf/ ,
%UprightFont = *-Regular ,
%BoldFont = *-Bold ,
%... ]
%{SourceSansPro}

\usepackage{tikz}
\usetikzlibrary{arrows,shapes,positioning,matrix}

%\hypersetup{colorlinks}% uncomment this line if you prefer colored hyperlinks (e.g., for onscreen viewing)

% helps floats stay within their sections
%\usepackage[section]{placeins}

%
% Temporary, shows float boundaries
%
%\usepackage{float}
%\floatstyle{boxed}
%\restylefloat{figure}

% Creative commons icons
\usepackage[scale=3.0]{ccicons} % This packages allows you to include the creative commons license logos.

%%
% Book metadata
\title{Texas Tech University\\Graduate Student\\Housing Report\\2013\thanks{Thanks to Dr. Peggy Miller for her inspiration.}}
\author[Kimberly Elmore and Jacek Jonca-Jasinski]{Kimberly Elmore, Jacek Jonca-Jasinski, and\\ the Graduate Student Advisory Council}
\publisher{Texas Tech University Graduate Student Advisory Council}

%Not queste sure why, it should help with text layout
%\usepackage{microtype}

%%
% For nicely typeset tabular material
\usepackage{booktabs}

%%
% For graphics / images
\usepackage{graphicx}
\setkeys{Gin}{width=\linewidth,totalheight=\textheight,keepaspectratio}
\graphicspath{{graphics/}}

% calculate tight bounding boxes
\usepackage[bbox,pdftopdf]{epspdfconversion}
%\usepackage{epstopdf}
%\epstopdfsetup{pdftopdf=true}
%\epstopdfDeclareGraphicsRule{.pdf}{pdf}{.pdf}{% 
%/usr/local/texlive/2012/bin/x86_64-linux/epspdf --bbox #1 \OutputFile
%}

% The fancyvrb package lets us customize the formatting of verbatim
% environments.  We use a slightly smaller font.
\usepackage{fancyvrb}
\fvset{fontsize=\normalsize}

%%
% Prints argument within hanging parentheses (i.e., parentheses that take
% up no horizontal space).  Useful in tabular environments.
\newcommand{\hangp}[1]{\makebox[0pt][r]{(}#1\makebox[0pt][l]{)}}

%%
% Prints an asterisk that takes up no horizontal space.
% Useful in tabular environments.
\newcommand{\hangstar}{\makebox[0pt][l]{*}}

%%
% Prints a trailing space in a smart way.
\usepackage{xspace}

% Prints the month name (e.g., January) and the year (e.g., 2008)
\newcommand{\monthyear}{%
  \ifcase\month\or January\or February\or March\or April\or May\or June\or
  July\or August\or September\or October\or November\or
  December\fi\space\number\year
}

% Prints an epigraph and speaker in sans serif, all-caps type.
\newcommand{\openepigraph}[2]{%
  %\sffamily\fontsize{14}{16}\selectfont
  \begin{fullwidth}
  \sffamily\large
  \begin{doublespace}
  \noindent\allcaps{#1}\\% epigraph
  \noindent\allcaps{#2}% author
  \end{doublespace}
  \end{fullwidth}
}

% Inserts a blank page
\newcommand{\blankpage}{\newpage\hbox{}\thispagestyle{empty}\newpage}

\usepackage{units}

% Typesets the font size, leading, and measure in the form of 10/12x26 pc.
\newcommand{\measure}[3]{#1/#2$\times$\unit[#3]{pc}}

% Macros for typesetting the documentation
\newcommand{\hlred}[1]{\textcolor{Maroon}{#1}}% prints in red
\newcommand{\hangleft}[1]{\makebox[0pt][r]{#1}}
\newcommand{\hairsp}{\hspace{1pt}}% hair space
\newcommand{\hquad}{\hskip0.5em\relax}% half quad space
\newcommand{\TODO}{\textcolor{red}{\bf TODO!}\xspace}
\newcommand{\ie}{\textit{i.\hairsp{}e.}\xspace}
\newcommand{\eg}{\textit{e.\hairsp{}g.}\xspace}
\newcommand{\na}{\quad--}% used in tables for N/A cells
\providecommand{\XeLaTeX}{X\lower.5ex\hbox{\kern-0.15em\reflectbox{E}}\kern-0.1em\LaTeX}
\newcommand{\tXeLaTeX}{\XeLaTeX\index{XeLaTeX@\protect\XeLaTeX}}
% \index{\texttt{\textbackslash xyz}@\hangleft{\texttt{\textbackslash}}\texttt{xyz}}
\newcommand{\tuftebs}{\symbol{'134}}% a backslash in tt type in OT1/T1
\newcommand{\doccmdnoindex}[2][]{\texttt{\tuftebs#2}}% command name -- adds backslash automatically (and doesn't add cmd to the index)
\newcommand{\doccmddef}[2][]{%
  \hlred{\texttt{\tuftebs#2}}\label{cmd:#2}%
  \ifthenelse{\isempty{#1}}%
    {% add the command to the index
      \index{#2 command@\protect\hangleft{\texttt{\tuftebs}}\texttt{#2}}% command name
    }%
    {% add the command and package to the index
      \index{#2 command@\protect\hangleft{\texttt{\tuftebs}}\texttt{#2} (\texttt{#1} package)}% command name
      \index{#1 package@\texttt{#1} package}\index{packages!#1@\texttt{#1}}% package name
    }%
}% command name -- adds backslash automatically
\newcommand{\doccmd}[2][]{%
  \texttt{\tuftebs#2}%
  \ifthenelse{\isempty{#1}}%
    {% add the command to the index
      \index{#2 command@\protect\hangleft{\texttt{\tuftebs}}\texttt{#2}}% command name
    }%
    {% add the command and package to the index
      \index{#2 command@\protect\hangleft{\texttt{\tuftebs}}\texttt{#2} (\texttt{#1} package)}% command name
      \index{#1 package@\texttt{#1} package}\index{packages!#1@\texttt{#1}}% package name
    }%
}% command name -- adds backslash automatically
\newcommand{\docopt}[1]{\ensuremath{\langle}\textrm{\textit{#1}}\ensuremath{\rangle}}% optional command argument
\newcommand{\docarg}[1]{\textrm{\textit{#1}}}% (required) command argument
\newenvironment{docspec}{\begin{quotation}\ttfamily\parskip0pt\parindent0pt\ignorespaces}{\end{quotation}}% command specification environment
\newcommand{\docenv}[1]{\texttt{#1}\index{#1 environment@\texttt{#1} environment}\index{environments!#1@\texttt{#1}}}% environment name
\newcommand{\docenvdef}[1]{\hlred{\texttt{#1}}\label{env:#1}\index{#1 environment@\texttt{#1} environment}\index{environments!#1@\texttt{#1}}}% environment name
\newcommand{\docpkg}[1]{\texttt{#1}\index{#1 package@\texttt{#1} package}\index{packages!#1@\texttt{#1}}}% package name
\newcommand{\doccls}[1]{\texttt{#1}}% document class name
\newcommand{\docclsopt}[1]{\texttt{#1}\index{#1 class option@\texttt{#1} class option}\index{class options!#1@\texttt{#1}}}% document class option name
\newcommand{\docclsoptdef}[1]{\hlred{\texttt{#1}}\label{clsopt:#1}\index{#1 class option@\texttt{#1} class option}\index{class options!#1@\texttt{#1}}}% document class option name defined
\newcommand{\docmsg}[2]{\bigskip\begin{fullwidth}\noindent\ttfamily#1\end{fullwidth}\medskip\par\noindent#2}
\newcommand{\docfilehook}[2]{\texttt{#1}\index{file hooks!#2}\index{#1@\texttt{#1}}}
\newcommand{\doccounter}[1]{\texttt{#1}\index{#1 counter@\texttt{#1} counter}}

% Patch for the sols problem if not using nols
\renewcommand{\allcapsspacing}[1]{{\addfontfeature{LetterSpace=20.0}#1}}
\renewcommand{\smallcapsspacing}[1]{{\addfontfeature{LetterSpace=5.0}#1}}
\renewcommand{\textsc}[1]{\smallcapsspacing{\textsmallcaps{#1}}}
\renewcommand{\smallcaps}[1]{\smallcapsspacing{\scshape\MakeTextLowercase{#1}}}

% Generates the index
\usepackage{makeidx}
\makeindex

%helps fit more stuff on a page
%\renewcommand\floatpagefraction{.9}
%\renewcommand\topfraction{.9}
%\renewcommand\bottomfraction{.9}
%\renewcommand\textfraction{.1}   
%\setcounter{totalnumber}{50}
%\setcounter{topnumber}{50}
%\setcounter{bottomnumber}{50}

\begin{document}
\pagenumbering{gobble}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt}

% Front matter
\frontmatter

% r.1 blank page
\blankpage

% v.2 epigraphs
\newpage\thispagestyle{empty}
\addcontentsline{toc}{chapter}{Executive Summary}
{\huge Executive Summary}
%\epspdfconversioncmdline
\paragraph{%
Need for Graduate Student Housing.} Graduate students believe that a graduate dorm is needed on our campus but only if done right. Graduate students are still on the fence with regard to whether they would actually choose to live in the graduate student dorm and the decisive factors are cost and the dormitory population.
%\vfill
\paragraph{%
Cost.} Majority of respondents expect a graduate student dorm to offer accommodations with a lower price tag than off-campus locations. Most of the respondents currently pay between \$400 and \$800 a month in combined rent and utilities with the largest group falling between \$400 and \$600. Respondents report to currently live in 1-3 bedroom apartments and single family houses and if moving to a graduate dorm would be most interested in single-bedroom apartments, with efficiency and 2 bedroom shared units being a second choice.
%\vfill
\paragraph{%
Dormitory Population.} Many respondents indicated that they would not choose to live in a combined graduate and undergraduate housing but have no qualms about living in the vicinity of an undergraduate dorm.
%\vfill
\paragraph{%
Amenities.} Respondents found amenities such as modern appliances, minimal grocery/convenience store, and an optional dining plan a plus. 
\paragraph{%
Recommendations.} This is a placeholder for the summary of the recommendations.  
% r.3 full title page
\maketitle

% v.4 copyright page
\newpage
\begin{fullwidth}
~\vfill
\thispagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{\baselineskip}
\par Some rights reserved under the Creative Commons Attribution-Share Alike 3.0 Unported license.
\par \ccbysa
\par (cc) \the\year\ Texas Tech University Graduate Student Advisory Council

\par Published by the Texas Tech University Graduate Student Advisory Council

\par\textit{First printing, \monthyear}
\end{fullwidth}

% r.5 contents
\tableofcontents

\listoffigures

\listoftables

% r.7 dedication
\cleardoublepage
~\vfill
\begin{doublespace}
\noindent\fontsize{18}{22}\selectfont\itshape
\nohyphenation
Dedicated to those who appreciate \LaTeX{} 
and the work of \mbox{Edward R.~Tufte} 
and \mbox{Donald E.~Knuth}.
\end{doublespace}
\vfill
\vfill


% r.9 introduction
\cleardoublepage


%### KNIT R SETTINGS ###
<<include=FALSE>>=
opts_chunk$set(concordance=TRUE)#,dev='tikz')
@
%<<MainSettings,echo=FALSE,cache=FALSE>>=
%require("knitr")
%setwd("/home/zephyr/Dropbox/latex-typesetting/graduate-housing-survey")
%#opts_knit$set(progress = FALSE, verbose = FALSE) # works better with Kile
%opts_chunk$set(
%  concordance=TRUE,
%  cache=FALSE,
%   tidy=TRUE,
%   echo=FALSE,
%   message=FALSE,
%   dev="pdf",
%   fig.path="plots/plot",                                         # puts all figures in a folder in the current directory called "graphics." If you use this, you need to create the graphics folder first. It also starts each figure's filename with "plot"
%   fig.lp = "",                                                                   # defines prefix for figure labels
%#   out.width=".8\\textwidth",
%#   fig.keep="high",
%#   fig.show="hold",
%#   fig.align="center",
%   dpi="200",
%   comment=NA)                                                      # Suppresses "##" in R output. The "##" is useful if you want people to be able to copy and paste your code in the output file, though.
%@

%<<eval=TRUE,echo=FALSE,results='hide',warning=FALSE,message=FALSE,error=FALSE>>=

\chapter{Introduction}
{\huge The WITCH}
\par This report is the first is a series addressing the \textbf{WITCH}: (\textbf{W})aivers, (\textbf{I})nsurance, (\textbf{T})ransportation, (\textbf{C})hildcare, and (\textbf{H})ousing -- the "BIG 5" recurring challenges faced by graduate students at Texas Tech University.

\par While most of the WITCHes are not new to this campus they are hard to tackle. The goal of this report series is to research the WITCHES and present recommendations for driving them out of Texas Tech University for good and for the good of all of us!

\par Proposed recommendations to the 5 challenges need to meet two essential criteria:
\begin{enumerate}[I]%for capital roman numbers.
%\begin{enumerate}
\item First, they will be grounded in the empirical data we collect in the form of surveys and comparisons with the peer institutions: those in the Big 12, State fo Texas, and more generally institutions demonstrating similar characteristics to Texas Tech.
\item Second, they need to be pragmatic, rational, and feasible. We all know that if we lived in an ideal world the resources at university's disposal would have been unlimited and graduate students would have had all and everything they need or want. Unfortunately, we don't live in an ideal world and the limited resources we have need to be alocated wisely and in a pragmatic and logical way.
\end{enumerate}
\paragraph{%
Waivers, Tuition, and Assistantships.} Here is a placeholder for a quick discussion of recent
issues with Waivers, cost of tuition, and Assistantships%

\paragraph{%
Insurance.} Health insurance struggles here %

\paragraph{%
Transportation and Parking.} Busing to appartment complexes, bus schedules at night, permits for teaching assistants %

\paragraph{%
Childcare.} On-campus or in the proximity. 

\paragraph{%
Housing.} On campus graduate student housing.  

\chapter{Method and Sample Characteristics}

\section{Background}
\par On December 3, 2012, the Graduate Student Advisory Council sent 4769 e-mail invitations to participate in the online Graduate Student Housing survey. Specifically, invitations were sent to all graduate students enrolled on the Lubbock campus. This report presents results of this survey accompanied by recommendations for development of graduate student campus housing on Texas Tech University campus. The Graduate Student Housing Report is organized into four parts:
\par (1) Method and Sample Characteristics
\par (2) Current Graduate Student Housing Characteristics
\par (3) Graduate Student Housing Expectations
\par (4) Summary of Survey Results and Recommendations
\par The section that follows discusses methodology of this survey and describes characteristics of the sample of graduate students who participated in this survey. The next part of this survey is describes present housing arrangements of graduate students. Graduate Student Housing Expectations part reports housing preferences expressed by graduate students and the Recommendations part concluding this report summarizes survey results and provides suggestions for development of the graduate student housing on Texas Tech campus. 

\section{Method}
\par We received responses from 5 percent of our sample within one hour of opening the survey, with 18.2 percent responding by the survey's close on December 13, 2012.
\par The Graduate Student Housing survey consisted of 18 questions, 8 demographic and 10 opinion questions about the current housing situations of and future on-campus housing for graduate students at Texas Tech University.

\section{Sample Characteristics}
\subsection{Age and Gender}

<<hideme, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Load Libraries
suppressMessages(require(knitr))
suppressMessages(library(ggplot2))
suppressMessages(library(xtable))
suppressMessages(library(catspec))
suppressMessages(require(grid))

# Cleanup
#rm(object)
#rm(housingsurvey.df)
#rm(housingsurveydata12102012.anonymized)
#rm(newdata)
#rm(dat)
#rm(newtable)
#rm(Agetable)
#rm(object)
#rm(formatedagetable)

# Load data
housingsurveydata12142012.anonymized <- read.csv("/home/zephyr/Dropbox/latex-typesetting/graduate-housing-survey/data/housingsurveydata12142012-anonymized.csv")
#load("/home/zephyr/Dropbox/latex-typesetting/graduate-housing-survey/graduate-housing-data/housingsurveydata12102012.anonymized.RData")
housingsurvey.df <- data.frame(housingsurveydata12142012.anonymized)
names(housingsurvey.df) <- c("RespondentID", "Age", "Gender", "Level", "Levelother", "Fulltime", "International", "Residencetype", "Residencetypeother", "Householdsize", "Rent", "Needfordorm", "Ifavailable", "Q11efficiency", "Q111br", "Q112br", "Q113br", "Q11not", "Q11other", "Q12childcare", "Q12playground", "Q12entertainment", "Q12alcohol", "Q12cost", "Q12appliances", "Q12grocery", "Q12dining", "Q12other", "Q12openended", "Wouldyoulive", "Howmuch", "Withundergrads", "Nexttoundergrads", "Transportation", "Transportationother", "Architectsother")

# drop missing cases & misc
#newdata <- housingsurvey.df[ which(housingsurvey.df$Age!=""), ]
#newdata$Age <- droplevels(newdata$Age)

newdata <- housingsurvey.df[ which((housingsurvey.df$Gender=='Male' | housingsurvey.df$Gender=='Female') & housingsurvey.df$Age!=""), ]
newdata$Gender <- droplevels(newdata$Gender)
newdata$Age <- droplevels(newdata$Age)

# Age
Agenewdata <- housingsurvey.df[ which(housingsurvey.df$Age!=""), ]
Agenewdata$Age <- droplevels(Agenewdata$Age)
Agetable <- ctab(Agenewdata$Age)
Ageobject <- print(Agetable,addmargins=FALSE,dec.places=0)
Agedat <- as.data.frame(Ageobject)
Agenewtable <- data.frame(Agedat$Freq[1:5], Agedat$Freq[6:10])
rownames(Agenewtable) <- Agedat$Var1[1:5]
colnames(Agenewtable) <- c('Count', 'Percentage')
#formatedagetable <- xtable(newtable, digits=0)

#newdata <- housingsurvey.df[ which(housingsurvey.df$Gender!=""), ]
#newdata$Gender <- droplevels(newdata$Gender)
Gendertable <- ctab(newdata$Gender)
Genderobject <- print(Gendertable,addmargins=FALSE,dec.places=0)
Genderdat <- as.data.frame(Genderobject)
Gendernewtable <- data.frame(Genderdat$Freq[1:2], Genderdat$Freq[3:4])
rownames(Gendernewtable) <- Genderdat$Var1[1:2]
colnames(Gendernewtable) <- c('Count', 'Percentage')
@

\begin{figure}[!htb]
\caption{Distribution of age and gender of participants in our sample\newline
\scriptsize{\newline
Approximately half of the respondents fall between the ages of 26 and 35 years old with additional one-third between the ages of 21 and 25. While sample consist of more female than male respondents the distribution of age characteristics across genders is very similar.
}}
%\vspace{-100pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraph, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", out.width="\\textwidth", fig.lp="fig:", fig.cap = ''>>=
#print(formatedagetable)
#par(mar=c(0,0,0,0)) # Remove unnecessary margins
plot <- ggplot(newdata, aes(x = factor(1), fill=Age)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('Number of Respondents') + labs(fill='Response') + facet_grid(facets=. ~ Gender)
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}
%\vspace{-115pt}
%
% Other PIE polar Chart examples 
% http://docs.ggplot2.org/current/coord_polar.html
%

%
% Age Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Age of survey respondents}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table]
{
Age & Number of Respondents & Percent \%\\ 
\Sexpr{rownames(Agenewtable)[1]} & \Sexpr{Agenewtable[[1]][[1]]} &  \Sexpr{Agenewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Agenewtable)[2]} & \Sexpr{Agenewtable[[1]][[2]]} &  \Sexpr{Agenewtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Agenewtable)[3]} & \Sexpr{Agenewtable[[1]][[3]]} &  \Sexpr{Agenewtable[[2]][[3]]}\% \\  
\Sexpr{rownames(Agenewtable)[4]} & \Sexpr{Agenewtable[[1]][[4]]} &  \Sexpr{Agenewtable[[2]][[4]]}\% \\  
\Sexpr{rownames(Agenewtable)[5]} & \Sexpr{Agenewtable[[1]][[5]]} &  \Sexpr{Agenewtable[[2]][[5]]}\% \\  
};
\normalsize
\end{tikzpicture}
\end{table}
\vspace{-10pt}

%
% Gender Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
  rectangle,
  draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.6ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Gender of survey respondents}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
Gender & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Gendernewtable)[1]} & \Sexpr{Gendernewtable[[1]][[1]]} &  \Sexpr{Gendernewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Gendernewtable)[2]} & \Sexpr{Gendernewtable[[1]][[2]]} &  \Sexpr{Gendernewtable[[2]][[2]]}\% \\ 
};
\end{tikzpicture}
\end{table}
%\vspace{-10pt}

%
% Level of Study
%

\subsection{Level of Study}

<<hidemeLevel, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Level
levelnewdata <- housingsurvey.df[ which(housingsurvey.df$Level!=""), ]
levelnewdata <- droplevels(levelnewdata)
levels(levelnewdata$Level) <- c("Doctoral", "Graduate Certificate", "Graduate Non-Degree", "Masters", "Post-Graduate")
Leveltable <- ctab(levelnewdata$Level)
Levelobject <- print(Leveltable,addmargins=FALSE,dec.places=0)
Leveldat <- as.data.frame(Levelobject)
Levelnewtable <- data.frame(Leveldat$Freq[1:5], Leveldat$Freq[6:10])
rownames(Levelnewtable) <- Leveldat$Var1[1:5]
colnames(Levelnewtable) <- c('Count', 'Percentage')
#formatedleveltable <- xtable(newtable, digits=0)
#print(formatedleveltable)
@

\begin{figure}[!htb]
\caption{Level of study of participants\newline
\scriptsize{\newline
space for description}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphlevel, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
#print(formatedagetable)
plot <- ggplot(levelnewdata, aes(x = factor(1), fill=Level)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Response')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
  rectangle,
  draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=8.3ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Participants by level of study}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table]
{
Age & Number of Respondents & Percent \%\\ 
\Sexpr{rownames(Levelnewtable)[1]} & \Sexpr{Levelnewtable[[1]][[1]]} &  \Sexpr{Levelnewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Levelnewtable)[2]} & \Sexpr{Levelnewtable[[1]][[2]]} &  \Sexpr{Levelnewtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Levelnewtable)[3]} & \Sexpr{Levelnewtable[[1]][[3]]} &  \Sexpr{Levelnewtable[[2]][[3]]}\% \\  
\Sexpr{rownames(Levelnewtable)[4]} & \Sexpr{Levelnewtable[[1]][[4]]} &  \Sexpr{Levelnewtable[[2]][[4]]}\% \\  
\Sexpr{rownames(Levelnewtable)[5]} & \Sexpr{Levelnewtable[[1]][[5]]} &  \Sexpr{Levelnewtable[[2]][[5]]}\% \\  
};
\normalsize
\end{tikzpicture}
\end{table}

\subsection{Enrollment Status}

<<hidemeFulltime, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Fulltime
newdata <- housingsurvey.df[ which(housingsurvey.df$Fulltime!=""), ]
newdata$Fulltime <- droplevels(newdata$Fulltime)
Fulltimetable <- ctab(newdata$Fulltime)
Fulltimeobject <- print(Fulltimetable,addmargins=FALSE,dec.places=0)
Fulltimedat <- as.data.frame(Fulltimeobject)
Fulltimenewtable <- data.frame(Fulltimedat$Freq[1:2], Fulltimedat$Freq[3:4])
rownames(Fulltimenewtable) <- Fulltimedat$Var1[1:2]
colnames(Fulltimenewtable) <- c('Count', 'Percentage')
@

\begin{figure}[!htb]
\caption{Enrollment status.\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphFulltime, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(newdata, aes(x = factor(1), fill=Fulltime)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Response')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Fulltime Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
  rectangle,
  draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Enrollment Status}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
Fulltime & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Fulltimenewtable)[1]} & \Sexpr{Fulltimenewtable[[1]][[1]]} &  \Sexpr{Fulltimenewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Fulltimenewtable)[2]} & \Sexpr{Fulltimenewtable[[1]][[2]]} &  \Sexpr{Fulltimenewtable[[2]][[2]]}\% \\ 
};
\end{tikzpicture}
\end{table}

\subsection{Origin}
<<hidemeInternational, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# International
newdata <- housingsurvey.df[ which(housingsurvey.df$International!=""), ]
newdata$International <- droplevels(newdata$International)
Internationaltable <- ctab(newdata$International)
Internationalobject <- print(Internationaltable,addmargins=FALSE,dec.places=0)
Internationaldat <- as.data.frame(Internationalobject)
Internationalnewtable <- data.frame(Internationaldat$Freq[1:2], Internationaldat$Freq[3:4])
rownames(Internationalnewtable) <- Internationaldat$Var1[1:2]
colnames(Internationalnewtable) <- c('Count', 'Percentage')
@

\begin{figure}[!htb]
\caption{Are you an International Student?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphInternational, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(newdata, aes(x = factor(1), fill=International)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='International?')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% International Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
  rectangle,
  draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Origin}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
International & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Internationalnewtable)[1]} & \Sexpr{Internationalnewtable[[1]][[1]]} &  \Sexpr{Internationalnewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Internationalnewtable)[2]} & \Sexpr{Internationalnewtable[[1]][[2]]} &  \Sexpr{Internationalnewtable[[2]][[2]]}\% \\ 
};
\end{tikzpicture}
\end{table}

\chapter{Current Graduate Student Housing Characteristics}
\section{Type of Residence}

<<hidemeResidencetype, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Residencetype
Residencetypenewdata <- housingsurvey.df[ which(housingsurvey.df$Residencetype!=""), ]
Residencetypenewdata$Residencetype <- droplevels(Residencetypenewdata$Residencetype)
Residencetypetable <- ctab(Residencetypenewdata$Residencetype)
Residencetypeobject <- print(Residencetypetable,addmargins=FALSE,dec.places=0)
Residencetypedat <- as.data.frame(Residencetypeobject)
Residencetypenewtable <- data.frame(Residencetypedat$Freq[1:7], Residencetypedat$Freq[8:14])
rownames(Residencetypenewtable) <- Residencetypedat$Var1[1:7]
rownames(Residencetypenewtable) <- c("Apartment", "Condominium", "Duplex", "On-campus housing", "Other", "Single-family house", "Townhouse")
colnames(Residencetypenewtable) <- c('Count', 'Percentage')
#formatedagetable <- xtable(newtable, digits=0)
@

\begin{figure}[!htb]
\caption{What type of residence do you live in?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-80pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphResidencetype, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
#print(formatedagetable)
plot <- ggplot(Residencetypenewdata, aes(x = factor(1), fill=Residencetype)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Response')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Residencetype Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
  rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
              	minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
                minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 7/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 8/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        }
    }
}

\begin{table}[!htb]
\caption{Participants by residence}
%\vspace{-20pt}
\begin{tikzpicture}\matrix (first) [table]
{
Residence Type & Number of Respondents & Percent \%\\ 
\Sexpr{rownames(Residencetypenewtable)[1]} & \Sexpr{Residencetypenewtable[[1]][[1]]} &  \Sexpr{Residencetypenewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Residencetypenewtable)[2]} & \Sexpr{Residencetypenewtable[[1]][[2]]} &  \Sexpr{Residencetypenewtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Residencetypenewtable)[3]} & \Sexpr{Residencetypenewtable[[1]][[3]]} &  \Sexpr{Residencetypenewtable[[2]][[3]]}\% \\  
\Sexpr{rownames(Residencetypenewtable)[4]} & \Sexpr{Residencetypenewtable[[1]][[4]]} &  \Sexpr{Residencetypenewtable[[2]][[4]]}\% \\  
\Sexpr{rownames(Residencetypenewtable)[5]} & \Sexpr{Residencetypenewtable[[1]][[5]]} &  \Sexpr{Residencetypenewtable[[2]][[5]]}\% \\  
\Sexpr{rownames(Residencetypenewtable)[6]} & \Sexpr{Residencetypenewtable[[1]][[6]]} &  \Sexpr{Residencetypenewtable[[2]][[6]]}\% \\  
\Sexpr{rownames(Residencetypenewtable)[7]} & \Sexpr{Residencetypenewtable[[1]][[7]]} &  \Sexpr{Residencetypenewtable[[2]][[7]]}\% \\  
};
\normalsize
\end{tikzpicture}
\end{table}

\section{Size of Residence}

<<hidemeHouseholdsize, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Householdsize
Householdsizenewdata <- housingsurvey.df[ which(housingsurvey.df$Householdsize!=""), ]
Householdsizenewdata$Householdsize <- droplevels(Householdsizenewdata$Householdsize)
Householdsizetable <- ctab(Householdsizenewdata$Householdsize)
Householdsizeobject <- print(Householdsizetable,addmargins=FALSE,dec.places=0)
Householdsizedat <- as.data.frame(Householdsizeobject)
Householdsizenewtable <- data.frame(Householdsizedat$Freq[1:5], Householdsizedat$Freq[6:10])
rownames(Householdsizenewtable) <- Householdsizedat$Var1[1:5]
rownames(Householdsizenewtable) <- c("1 bedroom", "2 bedrooms", "3 bedrooms", "4+ bedrooms", "Studio / Efficiency")
colnames(Householdsizenewtable) <- c('Count', 'Percentage')
#formatedagetable <- xtable(newtable, digits=0)
@

\begin{figure}[!htb]
\caption{What is the size of your household?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphHouseholdsize, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
#print(formatedagetable)
plot <- ggplot(Householdsizenewdata, aes(x = factor(1), fill=Householdsize)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Response')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Householdsize Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
  	minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
                minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Participants by Household Size}
%\vspace{-20pt}
\begin{tikzpicture}\matrix (first) [table]
{
Residence Type & Number of Respondents & Percent \%\\ 
\Sexpr{rownames(Householdsizenewtable)[1]} & \Sexpr{Householdsizenewtable[[1]][[1]]} &  \Sexpr{Householdsizenewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Householdsizenewtable)[2]} & \Sexpr{Householdsizenewtable[[1]][[2]]} &  \Sexpr{Householdsizenewtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Householdsizenewtable)[3]} & \Sexpr{Householdsizenewtable[[1]][[3]]} &  \Sexpr{Householdsizenewtable[[2]][[3]]}\% \\  
\Sexpr{rownames(Householdsizenewtable)[4]} & \Sexpr{Householdsizenewtable[[1]][[4]]} &  \Sexpr{Householdsizenewtable[[2]][[4]]}\% \\  
\Sexpr{rownames(Householdsizenewtable)[5]} & \Sexpr{Householdsizenewtable[[1]][[5]]} &  \Sexpr{Householdsizenewtable[[2]][[5]]}\% \\  
};
\normalsize
\end{tikzpicture}
\end{table}

\section{Cost of Rent and Utilities}

<<hidemeRent, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Rent
Rentnewdata <- housingsurvey.df[ which(housingsurvey.df$Rent!=""), ]
Rentnewdata$Rent <- droplevels(Rentnewdata$Rent)
Renttable <- ctab(Rentnewdata$Rent)
Rentobject <- print(Renttable,addmargins=FALSE,dec.places=0)
Rentdat <- as.data.frame(Rentobject)
Rentnewtable <- data.frame(Rentdat$Freq[1:5], Rentdat$Freq[6:10])
rownames(Rentnewtable) <- Rentdat$Var1[1:5]
rownames(Rentnewtable) <- c("1,000+ USD", "400 to 600 USD", "600 to 800 USD", "800 to 1,000 USD", "Less than 400 USD")
colnames(Rentnewtable) <- c('Count', 'Percentage')
#formatedagetable <- xtable(newtable, digits=0)
@

\begin{figure}[!htb]
\caption{How much do you pay in rent?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphRent, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
#print(formatedagetable)
plot <- ggplot(Rentnewdata, aes(x = factor(1), fill=Rent)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Response')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Rent Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Current cost of rent}
%\vspace{-20pt}
\begin{tikzpicture}\matrix (first) [table]
{
Cost & Number of Respondents & Percent \%\\ 
\Sexpr{rownames(Rentnewtable)[1]} & \Sexpr{Rentnewtable[[1]][[1]]} &  \Sexpr{Rentnewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Rentnewtable)[2]} & \Sexpr{Rentnewtable[[1]][[2]]} &  \Sexpr{Rentnewtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Rentnewtable)[3]} & \Sexpr{Rentnewtable[[1]][[3]]} &  \Sexpr{Rentnewtable[[2]][[3]]}\% \\  
\Sexpr{rownames(Rentnewtable)[4]} & \Sexpr{Rentnewtable[[1]][[4]]} &  \Sexpr{Rentnewtable[[2]][[4]]}\% \\  
\Sexpr{rownames(Rentnewtable)[5]} & \Sexpr{Rentnewtable[[1]][[5]]} &  \Sexpr{Rentnewtable[[2]][[5]]}\% \\  
};
\normalsize
\end{tikzpicture}
\end{table}

\chapter{Graduate Student Housing Expectations}
\section{9. Is there a need for a graduate student residence hall on Texas Tech's campus?}

<<hidemeNeedfordorm, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Needfordorm
newdata <- housingsurvey.df[ which(housingsurvey.df$Needfordorm!=""), ]
newdata$Needfordorm <- droplevels(newdata$Needfordorm)
Needfordormtable <- ctab(newdata$Needfordorm)
Needfordormobject <- print(Needfordormtable,addmargins=FALSE,dec.places=0)
Needfordormdat <- as.data.frame(Needfordormobject)
Needfordormnewtable <- data.frame(Needfordormdat$Freq[1:2], Needfordormdat$Freq[3:4])
rownames(Needfordormnewtable) <- Needfordormdat$Var1[1:2]
colnames(Needfordormnewtable) <- c('Count', 'Percentage')
@

\begin{figure}[!htb]
\caption{Is there a need for on-campus graduate student housing?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphNeedfordorm, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(newdata, aes(x = factor(1), fill=Needfordorm)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Is it needed?')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Needfordorm Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
  rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        }
    }
}

\begin{table}[!htb]
\caption{Need for a new graduate dorm}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
Is it needed? & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Needfordormnewtable)[1]} & \Sexpr{Needfordormnewtable[[1]][[1]]} &  \Sexpr{Needfordormnewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Needfordormnewtable)[2]} & \Sexpr{Needfordormnewtable[[1]][[2]]} &  \Sexpr{Needfordormnewtable[[2]][[2]]}\% \\ 
};
\end{tikzpicture}
\end{table}

\section{10. If on-campus graduate housing had been available at the time you were admitted to Texas Tech, how likely would you have been to apply to live in such housing?}
<<hidemeIfavailable, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Ifavailable
newdata <- housingsurvey.df[ which(housingsurvey.df$Ifavailable!=""), ]
newdata$Ifavailable <- droplevels(newdata$Ifavailable)
Ifavailabletable <- ctab(newdata$Ifavailable)
Ifavailableobject <- print(Ifavailabletable,addmargins=FALSE,dec.places=0)
Ifavailabledat <- as.data.frame(Ifavailableobject)
Ifavailablenewtable <- data.frame(Ifavailabledat$Freq[1:2], Ifavailabledat$Freq[3:4])
rownames(Ifavailablenewtable) <- Ifavailabledat$Var1[1:2]
colnames(Ifavailablenewtable) <- c('Count', 'Percentage')
@

\begin{figure}[!htb]
\caption{If on-campus graduate housing had been available at the time you were admitted to Texas Tech, how likely would you have been to apply to live in such housing?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphIfavailable, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(newdata, aes(x = factor(1), fill=Ifavailable)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Ifavailable?')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Ifavailable Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        }
    }
}

\begin{table}[!htb]
\caption{Likelihood of applying for graduate housing at the time of admission}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
Is it needed? & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Ifavailablenewtable)[1]} & \Sexpr{Ifavailablenewtable[[1]][[1]]} &  \Sexpr{Ifavailablenewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Ifavailablenewtable)[2]} & \Sexpr{Ifavailablenewtable[[1]][[2]]} &  \Sexpr{Ifavailablenewtable[[2]][[2]]}\% \\ 
};
\end{tikzpicture}
\end{table}

\section{11. What types of residence would you be interested in?}

<<hidemeQ11, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=
temp <- cbind(newdata[14:18])
names(temp) <- c("same", "same", "same", "same", "same")
delme <- rbind(temp[1], temp[2], temp[3], temp[4], temp[5])
Q11 <- delme[ which(delme$same!=""), ]
Q11 <- droplevels(Q11)
Q11table <- ctab(Q11)
Q11object <- print(Q11table,addmargins=FALSE,dec.places=0)
Q11dat <- as.data.frame(Q11object)
Q11newtable <- data.frame(Q11dat$Freq[1:5], Q11dat$Freq[6:10])
rownames(Q11newtable) <- Q11dat$Q11[1:5]
colnames(Q11newtable) <- c('Count', 'Percentage')
@

\begin{figure}[!htb]
\caption{What type of residence are you interested in?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphQ11, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(, aes(x = factor(1), fill=Q11)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Housing preference')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Q11 Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Prefered type of residence}
%\vspace{-20pt}
\begin{tikzpicture}\matrix (first) [table]
{
Prefered Residence & Number of Respondents & Percent \%\\ 
\Sexpr{rownames(Q11newtable)[1]} & \Sexpr{Q11newtable[[1]][[1]]} &  \Sexpr{Q11newtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Q11newtable)[2]} & \Sexpr{Q11newtable[[1]][[2]]} &  \Sexpr{Q11newtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Q11newtable)[3]} & \Sexpr{Q11newtable[[1]][[3]]} &  \Sexpr{Q11newtable[[2]][[3]]}\% \\  
\Sexpr{rownames(Q11newtable)[4]} & \Sexpr{Q11newtable[[1]][[4]]} &  \Sexpr{Q11newtable[[2]][[4]]}\% \\  
\Sexpr{rownames(Q11newtable)[5]} & \Sexpr{Q11newtable[[1]][[5]]} &  \Sexpr{Q11newtable[[2]][[5]]}\% \\  
};
\normalsize
\end{tikzpicture}
\end{table}


\section{12. How important is each of the following for a graduate student residence hall?}

<<hidemeQ12, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=
# Q12
# Playground
Q12playgroundnewdata <- housingsurvey.df[ which(housingsurvey.df$Q12playground!=""), ]
Q12playgroundnewdata$Q12playground <- droplevels(Q12playgroundnewdata$Q12playground)
Q12playgroundnewdata$Q12playground<-relevel(Q12playgroundnewdata$Q12playground, ref='not important')
Q12playgroundnewdata$Q12playground<-relevel(Q12playgroundnewdata$Q12playground, ref='somewhat important')
Q12playgroundnewdata$Q12playground<-relevel(Q12playgroundnewdata$Q12playground, ref='important')
Q12playgroundnewdata$Q12playground<-relevel(Q12playgroundnewdata$Q12playground, ref='most important')
Q12playgroundtable <- ctab(Q12playgroundnewdata$Q12playground)
Q12playgroundobject <- print(Q12playgroundtable,addmargins=FALSE,dec.places=0)
Q12playgrounddat <- as.data.frame(Q12playgroundobject)
Q12playgroundnewtable <- data.frame(Q12playgrounddat$Freq[1:4], Q12playgrounddat$Freq[5:8])
rownames(Q12playgroundnewtable) <- Q12playgrounddat$Var1[1:4]
colnames(Q12playgroundnewtable) <- c('Count', 'Percentage')

# Entertainment
Q12entertainmentnewdata <- housingsurvey.df[ which(housingsurvey.df$Q12entertainment!=""), ]
Q12entertainmentnewdata$Q12entertainment <- droplevels(Q12entertainmentnewdata$Q12entertainment)
Q12entertainmentnewdata$Q12entertainment<-relevel(Q12entertainmentnewdata$Q12entertainment, ref='not important')
Q12entertainmentnewdata$Q12entertainment<-relevel(Q12entertainmentnewdata$Q12entertainment, ref='somewhat important')
Q12entertainmentnewdata$Q12entertainment<-relevel(Q12entertainmentnewdata$Q12entertainment, ref='important')
Q12entertainmentnewdata$Q12entertainment<-relevel(Q12entertainmentnewdata$Q12entertainment, ref='most important')
Q12entertainmenttable <- ctab(Q12entertainmentnewdata$Q12entertainment)
Q12entertainmentobject <- print(Q12entertainmenttable,addmargins=FALSE,dec.places=0)
Q12entertainmentdat <- as.data.frame(Q12entertainmentobject)
Q12entertainmentnewtable <- data.frame(Q12entertainmentdat$Freq[1:4], Q12entertainmentdat$Freq[5:8])
rownames(Q12entertainmentnewtable) <- Q12entertainmentdat$Var1[1:4]
colnames(Q12entertainmentnewtable) <- c('Count', 'Percentage')

# Alcohol
Q12alcoholnewdata <- housingsurvey.df[ which(housingsurvey.df$Q12alcohol!=""), ]
Q12alcoholnewdata$Q12alcohol <- droplevels(Q12alcoholnewdata$Q12alcohol)
Q12alcoholnewdata$Q12alcohol<-relevel(Q12alcoholnewdata$Q12alcohol, ref='not important')
Q12alcoholnewdata$Q12alcohol<-relevel(Q12alcoholnewdata$Q12alcohol, ref='somewhat important')
Q12alcoholnewdata$Q12alcohol<-relevel(Q12alcoholnewdata$Q12alcohol, ref='important')
Q12alcoholnewdata$Q12alcohol<-relevel(Q12alcoholnewdata$Q12alcohol, ref='most important')
Q12alcoholtable <- ctab(Q12alcoholnewdata$Q12alcohol)
Q12alcoholobject <- print(Q12alcoholtable,addmargins=FALSE,dec.places=0)
Q12alcoholdat <- as.data.frame(Q12alcoholobject)
Q12alcoholnewtable <- data.frame(Q12alcoholdat$Freq[1:4], Q12alcoholdat$Freq[5:8])
rownames(Q12alcoholnewtable) <- Q12alcoholdat$Var1[1:4]
colnames(Q12alcoholnewtable) <- c('Count', 'Percentage')

# Cost
Q12costnewdata <- housingsurvey.df[ which(housingsurvey.df$Q12cost!=""), ]
Q12costnewdata$Q12cost <- droplevels(Q12costnewdata$Q12cost)
Q12costnewdata$Q12cost<-relevel(Q12costnewdata$Q12cost, ref='not important')
Q12costnewdata$Q12cost<-relevel(Q12costnewdata$Q12cost, ref='somewhat important')
Q12costnewdata$Q12cost<-relevel(Q12costnewdata$Q12cost, ref='important')
Q12costnewdata$Q12cost<-relevel(Q12costnewdata$Q12cost, ref='most important')
Q12costtable <- ctab(Q12costnewdata$Q12cost)
Q12costobject <- print(Q12costtable,addmargins=FALSE,dec.places=0)
Q12costdat <- as.data.frame(Q12costobject)
Q12costnewtable <- data.frame(Q12costdat$Freq[1:4], Q12costdat$Freq[5:8])
rownames(Q12costnewtable) <- Q12costdat$Var1[1:4]
colnames(Q12costnewtable) <- c('Count', 'Percentage')

# appliances
Q12appliancesnewdata <- housingsurvey.df[ which(housingsurvey.df$Q12appliances!=""), ]
Q12appliancesnewdata$Q12appliances <- droplevels(Q12appliancesnewdata$Q12appliances)
Q12appliancesnewdata$Q12appliances<-relevel(Q12appliancesnewdata$Q12appliances, ref='not important')
Q12appliancesnewdata$Q12appliances<-relevel(Q12appliancesnewdata$Q12appliances, ref='somewhat important')
Q12appliancesnewdata$Q12appliances<-relevel(Q12appliancesnewdata$Q12appliances, ref='important')
Q12appliancesnewdata$Q12appliances<-relevel(Q12appliancesnewdata$Q12appliances, ref='most important')
Q12appliancestable <- ctab(Q12appliancesnewdata$Q12appliances)
Q12appliancesobject <- print(Q12appliancestable,addmargins=FALSE,dec.places=0)
Q12appliancesdat <- as.data.frame(Q12appliancesobject)
Q12appliancesnewtable <- data.frame(Q12appliancesdat$Freq[1:4], Q12appliancesdat$Freq[5:8])
rownames(Q12appliancesnewtable) <- Q12appliancesdat$Var1[1:4]
colnames(Q12appliancesnewtable) <- c('Count', 'Percentage')

# grocery
Q12grocerynewdata <- housingsurvey.df[ which(housingsurvey.df$Q12grocery!=""), ]
Q12grocerynewdata$Q12grocery <- droplevels(Q12grocerynewdata$Q12grocery)
Q12grocerynewdata$Q12grocery<-relevel(Q12grocerynewdata$Q12grocery, ref='not important')
Q12grocerynewdata$Q12grocery<-relevel(Q12grocerynewdata$Q12grocery, ref='somewhat important')
Q12grocerynewdata$Q12grocery<-relevel(Q12grocerynewdata$Q12grocery, ref='important')
Q12grocerynewdata$Q12grocery<-relevel(Q12grocerynewdata$Q12grocery, ref='most important')
Q12grocerytable <- ctab(Q12grocerynewdata$Q12grocery)
Q12groceryobject <- print(Q12grocerytable,addmargins=FALSE,dec.places=0)
Q12grocerydat <- as.data.frame(Q12groceryobject)
Q12grocerynewtable <- data.frame(Q12grocerydat$Freq[1:4], Q12grocerydat$Freq[5:8])
rownames(Q12grocerynewtable) <- Q12grocerydat$Var1[1:4]
colnames(Q12grocerynewtable) <- c('Count', 'Percentage')

# dining
Q12diningnewdata <- housingsurvey.df[ which(housingsurvey.df$Q12dining!=""), ]
Q12diningnewdata$Q12dining <- droplevels(Q12diningnewdata$Q12dining)
Q12diningnewdata$Q12dining<-relevel(Q12diningnewdata$Q12dining, ref='not important')
Q12diningnewdata$Q12dining<-relevel(Q12diningnewdata$Q12dining, ref='somewhat important')
Q12diningnewdata$Q12dining<-relevel(Q12diningnewdata$Q12dining, ref='important')
Q12diningnewdata$Q12dining<-relevel(Q12diningnewdata$Q12dining, ref='most important')
Q12diningtable <- ctab(Q12diningnewdata$Q12dining)
Q12diningobject <- print(Q12diningtable,addmargins=FALSE,dec.places=0)
Q12diningdat <- as.data.frame(Q12diningobject)
Q12diningnewtable <- data.frame(Q12diningdat$Freq[1:4], Q12diningdat$Freq[5:8])
rownames(Q12diningnewtable) <- Q12diningdat$Var1[1:4]
colnames(Q12diningnewtable) <- c('Count', 'Percentage')

# other
Q12othernewdata <- housingsurvey.df[ which(housingsurvey.df$Q12other!=""), ]
Q12othernewdata$Q12other <- droplevels(Q12othernewdata$Q12other)
Q12othernewdata$Q12other<-relevel(Q12othernewdata$Q12other, ref='not important')
Q12othernewdata$Q12other<-relevel(Q12othernewdata$Q12other, ref='somewhat important')
Q12othernewdata$Q12other<-relevel(Q12othernewdata$Q12other, ref='important')
Q12othernewdata$Q12other<-relevel(Q12othernewdata$Q12other, ref='most important')
Q12othertable <- ctab(Q12othernewdata$Q12other)
Q12otherobject <- print(Q12othertable,addmargins=FALSE,dec.places=0)
Q12otherdat <- as.data.frame(Q12otherobject)
Q12othernewtable <- data.frame(Q12otherdat$Freq[1:4], Q12otherdat$Freq[5:8])
rownames(Q12othernewtable) <- Q12otherdat$Var1[1:4]
colnames(Q12othernewtable) <- c('Count', 'Percentage')

suppressMessages(library(epicalc))

### recode the variables to factors ###
#recode(Q12playgroundnewdata$Q12playground, Q12entertainmentnewdata$Q12entertainment, Q12alcoholnewdata$Q12alcohol, Q12costnewdata$Q12cost, Q12appliancesnewdata$Q12appliances, Q12grocerynewdata$Q12grocery, Q12diningnewdata$Q12dining, Q12othernewdata$Q12other), c(1,2,3,4,5,6,7,8), c('not important','somewhat important','important','most important',NA,NA,NA,NA))

#attach(newdata)

### Combine recoded variables to a common vector
#Interest1<-c(Q12playground, Q12entertainment, Q12alcohol, Q12cost, Q12appliances, Q12grocery, Q12dining, Q12other)
Interest1 <- c(Q12playgroundnewdata$Q12playground, Q12entertainmentnewdata$Q12entertainment, Q12alcoholnewdata$Q12alcohol, Q12costnewdata$Q12cost, Q12appliancesnewdata$Q12appliances, Q12grocerynewdata$Q12grocery, Q12diningnewdata$Q12dining, Q12othernewdata$Q12other)

#Q12.df <- data.frame(c(Q12playgroundnewdata$Q12playground, Q12entertainmentnewdata$Q12entertainment, Q12alcoholnewdata$Q12alcohol, Q12costnewdata$Q12cost, Q12appliancesnewdata$Q12appliances, Q12grocerynewdata$Q12grocery, Q12diningnewdata$Q12dining, Q12othernewdata$Q12other))

### Create a second vector to label the first vector by original variable ###  

a1<-rep("Playground space", length(Q12playgroundnewdata$Q12playground))
a2<-rep("Entertainment spaces (e.g. movie theater)", length(Q12entertainmentnewdata$Q12entertainment))
a3<-rep("Alcohol allowed inside a residence", length(Q12alcoholnewdata$Q12alcohol))
a4<-rep("Low cost", length(Q12costnewdata$Q12cost))
a5<-rep("Modern appliances", length(Q12appliancesnewdata$Q12appliances)) 
a6<-rep("Minimal grocery store", length(Q12grocerynewdata$Q12grocery))
a7<-rep("Optional dining plan available", length(Q12diningnewdata$Q12dining))
a8<-rep("Other", length(Q12othernewdata$Q12other))

Interest2<-c(a1, a2, a3, a4, a5, a6, a7, a8)

## Shorter labels for polar coord plot

b1<-rep("Playground", length(Q12playgroundnewdata$Q12playground))
b2<-rep("Entertainment", length(Q12entertainmentnewdata$Q12entertainment))
b3<-rep("Alcohol", length(Q12alcoholnewdata$Q12alcohol))
b4<-rep("Cost", length(Q12costnewdata$Q12cost))
b5<-rep("Appliances", length(Q12appliancesnewdata$Q12appliances)) 
b6<-rep("Grocer", length(Q12grocerynewdata$Q12grocery))
b7<-rep("Dining plan", length(Q12diningnewdata$Q12dining))
b8<-rep("Other", length(Q12othernewdata$Q12other))

Interest3<-c(b1, b2, b3, b4, b5, b6, b7, b8)

### Make and save a new data frame from the three vectors ###
Interest.df<-cbind(Interest1, Interest2)
Interest.df<-as.data.frame(Interest.df)

write.csv(Interest.df, 'InterestDorm.csv')

#detach(Interest.df)
#attach(Interest.df)

#
# Adjust order
#
#Interest.df$Interest2<-relevel(Interest.df$Interest2, ref='Low cost')
#Interest.df$Interest2<-relevel(Interest.df$Interest2, ref='Modern appliances')
#Interest.df$Interest2<-relevel(Interest.df$Interest2, ref='Optional dining plan available')
#Interest.df$Interest2<-relevel(Interest.df$Interest2, ref='Alcohol allowed inside a residence')
@
\begin{figure}[!htb]
\caption{Important considerations in selecting housing.\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphQ12, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=

### Finally create the graph in ggplot2 ###

suppressMessages(library(ggplot2))
suppressMessages(library(RColorBrewer))

### Long Version for clarity
#p <- ggplot(Interest.df, aes(factor(Interest2), ..count..)) + geom_bar()
#p <- p + geom_bar((aes(fill=Interest1)))
#p <- p + coord_flip()
#p <- p + scale_y_continuous("", breaks=NULL)
#p <- p + scale_fill_manual(values = rev(brewer.pal(5, "Purples")), labels=c("Most Important", "Important", "Somewhat Important", "Not Important"))
#p <- p + xlab('') + ylab('') + labs(fill='')
#p

### Short Version
#ggplot(Interest.df, aes(factor(Interest2), ..count..)) + geom_bar((aes(fill=Interest1))) + coord_flip() + scale_y_continuous("", breaks=NULL) + scale_fill_manual(values = rev(brewer.pal(5, "Purples")), labels=c("Most Important", "Important", "Somewhat Important", "Not Important")) + xlab('') + ylab('') + labs(fill='')

### Short Version - non-flipped
#ggplot(Interest.df, aes(factor(Interest2), ..count..)) + geom_bar((aes(fill=Interest1))) + scale_y_continuous("", breaks=NULL) + scale_fill_manual(values = rev(brewer.pal(5, "Purples")), labels=c("Most Important", "Important", "Somewhat Important", "Not Important")) + xlab('') + ylab('') + labs(fill='') + theme(axis.text.x = element_text(angle = 90, hjust = 1))

# and add a analogous Polar coord plot with adjusted labels
# new df with adjusted labels
#Interest.df<-cbind(Interest1, Interest3)
#Interest.df<-as.data.frame(Interest.df)

#
# Polar coordinates stack bar graph
#
ggplot(Interest.df, aes(factor(Interest3), ..count..)) + geom_bar((aes(fill=Interest1))) + coord_flip() + scale_y_continuous("", breaks=NULL) + scale_fill_manual(values = rev(brewer.pal(5, "Purples")), labels=c("Most Important", "Important", "Somewhat Important", "Not Important")) + xlab('') + ylab('') + labs(fill='') + coord_polar()
@
\end{figure}
%
% Q13. How likely would you be to live in a graduate student only residence hall if Texas Tech offered one?
%

\section{Q13. How likely would you be to live in a graduate student only residence hall if Texas Tech offered one?}
<<hidemeWouldyoulive, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Wouldyoulive
newdata <- housingsurvey.df[ which(housingsurvey.df$Wouldyoulive!=""), ]
newdata$Wouldyoulive <- droplevels(newdata$Wouldyoulive)
Wouldyoulivetable <- ctab(newdata$Wouldyoulive)
Wouldyouliveobject <- print(Wouldyoulivetable,addmargins=FALSE,dec.places=0)
Wouldyoulivedat <- as.data.frame(Wouldyouliveobject)
Wouldyoulivenewtable <- data.frame(Wouldyoulivedat$Freq[1:3], Wouldyoulivedat$Freq[4:6])
rownames(Wouldyoulivenewtable) <- Wouldyoulivedat$Var1[1:3]
colnames(Wouldyoulivenewtable) <- c('Count', 'Percentage')
@
\begin{figure}[!htb]
\caption{Would you live in an on-campus graduate housing if it was available?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphWouldyoulive, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(newdata, aes(x = factor(1), fill=Wouldyoulive)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Wouldyoulive?')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Wouldyoulive Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
		minimum height=7.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
		minimum height=7.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
		minimum height=7.5ex
            }
        }
    }
}

\begin{table}[!htb]
\caption{Would you live in on-campus graduate housing?}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
Would you live there? & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Wouldyoulivenewtable)[1]} & \Sexpr{Wouldyoulivenewtable[[1]][[1]]} &  \Sexpr{Wouldyoulivenewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Wouldyoulivenewtable)[2]} & \Sexpr{Wouldyoulivenewtable[[1]][[2]]} &  \Sexpr{Wouldyoulivenewtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Wouldyoulivenewtable)[3]} & \Sexpr{Wouldyoulivenewtable[[1]][[3]]} &  \Sexpr{Wouldyoulivenewtable[[2]][[3]]}\% \\ 
};
\end{tikzpicture}
\end{table}
%
% 14. Would you expect to pay more or less for rent and utilities in a graduate student residence hall than you pay now?
%


\section{Q14. Would you expect to pay more or less for rent and utilities in a graduate student residence hall than you pay now?}
<<hidemeHowmuch, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Howmuch
newdata <- housingsurvey.df[ which(housingsurvey.df$Howmuch!=""), ]
newdata$Howmuch <- droplevels(newdata$Howmuch)
Howmuchtable <- ctab(newdata$Howmuch)
Howmuchobject <- print(Howmuchtable,addmargins=FALSE,dec.places=0)
Howmuchdat <- as.data.frame(Howmuchobject)
Howmuchnewtable <- data.frame(Howmuchdat$Freq[1:3], Howmuchdat$Freq[4:6])
rownames(Howmuchnewtable) <- Howmuchdat$Var1[1:3]
colnames(Howmuchnewtable) <- c('Count', 'Percentage')
@
\begin{figure}[!htb]
\caption{How much would you expect to pay for on-campus graduate housing?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphHowmuch, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(newdata, aes(x = factor(1), fill=Howmuch)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Howmuch?')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% How much Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
  rectangle,
  draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
		minimum height=7.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
		minimum height=7.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
		minimum height=7.5ex
            }
        }
    }
}

\begin{table}[!htb]
\caption{Expected cost of graduate housing}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
How much? & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Howmuchnewtable)[1]} & \Sexpr{Howmuchnewtable[[1]][[1]]} &  \Sexpr{Howmuchnewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Howmuchnewtable)[2]} & \Sexpr{Howmuchnewtable[[1]][[2]]} &  \Sexpr{Howmuchnewtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Howmuchnewtable)[3]} & \Sexpr{Howmuchnewtable[[1]][[3]]} &  \Sexpr{Howmuchnewtable[[2]][[3]]}\% \\ 
};
\end{tikzpicture}
\end{table}
%
% 15. Would you choose NOT to live in a graduate residence hall if the university filled open rooms with undergraduate students?
%
\section{Q15. Would you choose NOT to live in a graduate residence hall if the university filled open rooms with undergraduate students?}

<<hidemeWithundergrads, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Withundergrads
newdata <- housingsurvey.df[ which(housingsurvey.df$Withundergrads!=""), ]
newdata$Withundergrads <- droplevels(newdata$Withundergrads)
Withundergradstable <- ctab(newdata$Withundergrads)
Withundergradsobject <- print(Withundergradstable,addmargins=FALSE,dec.places=0)
Withundergradsdat <- as.data.frame(Withundergradsobject)
Withundergradsnewtable <- data.frame(Withundergradsdat$Freq[1:2], Withundergradsdat$Freq[3:4])
rownames(Withundergradsnewtable) <- Withundergradsdat$Var1[1:2]
colnames(Withundergradsnewtable) <- c('Count', 'Percentage')
@

\begin{figure}[!htb]
\caption{Would you live in a dorm with undergraduate students?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphWithundergrads, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(newdata, aes(x = factor(1), fill=Withundergrads)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + scale_fill_discrete(name="Would NOT live with\nundergraduates?", labels=c("No =  would live", "Yes = would not live"))
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Withundergrads Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        }
    }
}

\begin{table}[!htb]
\caption{Would you live in mixed graduate-undergraduate housing?}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
Would you NOT live with undergraduate students? & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Withundergradsnewtable)[1]} & \Sexpr{Withundergradsnewtable[[1]][[1]]} &  \Sexpr{Withundergradsnewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Withundergradsnewtable)[2]} & \Sexpr{Withundergradsnewtable[[1]][[2]]} &  \Sexpr{Withundergradsnewtable[[2]][[2]]}\% \\ 
};
\end{tikzpicture}
\end{table}

%
% 16. Would you choose NOT to live in a graduate residence hall if it were next to an undergraduate residence hall?
%
\section{Q16. Would you choose NOT to live in a graduate residence hall if it were next to an undergraduate residence hall?}

<<hidemeNexttoundergrads, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Nexttoundergrads
newdata <- housingsurvey.df[ which(housingsurvey.df$Nexttoundergrads!=""), ]
newdata$Nexttoundergrads <- droplevels(newdata$Nexttoundergrads)
Nexttoundergradstable <- ctab(newdata$Nexttoundergrads)
Nexttoundergradsobject <- print(Nexttoundergradstable,addmargins=FALSE,dec.places=0)
Nexttoundergradsdat <- as.data.frame(Nexttoundergradsobject)
Nexttoundergradsnewtable <- data.frame(Nexttoundergradsdat$Freq[1:2], Nexttoundergradsdat$Freq[3:4])
rownames(Nexttoundergradsnewtable) <- Nexttoundergradsdat$Var1[1:2]
colnames(Nexttoundergradsnewtable) <- c('Count', 'Percentage')
@

\begin{figure}[!htb]
\caption{Would you live in graduate student housing located close to undergraduate student housing?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphNexttoundergrads, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
plot <- ggplot(newdata, aes(x = factor(1), fill=Nexttoundergrads)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + scale_fill_discrete(name="Would NOT live next\nto undergraduates?", labels=c("No =  would live", "Yes = would not live"))
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

%
% Nexttoundergrads Table
%

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        }
    }
}

\begin{table}[!htb]
\caption{Would you live in graduate housing adjacent to undegraduate housing?}
%\vspace{-20pt}
\begin{tikzpicture}
\matrix (first) [table,text width=6em]
{
Would you NOT live with undergraduate students? & Number of Respondents & Percent \% \\ 
\Sexpr{rownames(Nexttoundergradsnewtable)[1]} & \Sexpr{Nexttoundergradsnewtable[[1]][[1]]} &  \Sexpr{Nexttoundergradsnewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Nexttoundergradsnewtable)[2]} & \Sexpr{Nexttoundergradsnewtable[[1]][[2]]} &  \Sexpr{Nexttoundergradsnewtable[[2]][[2]]}\% \\ 
};
\end{tikzpicture}
\end{table}

%
% 17. How would you usually move around campus if the graduate student residence hall were on campus but a mile or more from the Student Union Building (SUB)?
%

\section{Q17. How would you usually move around campus if the graduate student residence hall were on campus but a mile or more from the Student Union Building (SUB)?}

<<hidemeTransportation, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, errors=FALSE, results="hide">>=

# Transportation
Transportationnewdata <- housingsurvey.df[ which(housingsurvey.df$Transportation!=""), ]
Transportationnewdata <- droplevels(Transportationnewdata)
#Transportations(Transportationnewdata$Transportation) <- c("Bike", "Bus", "Car", "Walk", "Other")
Transportationtable <- ctab(Transportationnewdata$Transportation)
Transportationobject <- print(Transportationtable,addmargins=FALSE,dec.places=0)
Transportationdat <- as.data.frame(Transportationobject)
Transportationnewtable <- data.frame(Transportationdat$Freq[1:4], Transportationdat$Freq[5:8])
rownames(Transportationnewtable) <- c("Bike", "Bus", "Car", "Walk")
colnames(Transportationnewtable) <- c('Count', 'Percentage')
#formatedTransportationtable <- xtable(newtable, digits=0)
#print(formatedTransportationtable)
trabsportationothercount <- length(housingsurvey.df$Transportationother[ which(housingsurvey.df$Transportationother!="") ])
trabsportationotherlenghth <- length(housingsurvey.df$Transportationother)
trabsportationotherpercent <- trabsportationothercount/trabsportationotherlenghth
percent <- function(x, digits = 2, format = "f", ...)
{
  paste(formatC(100 * x, format = format, digits = digits, ...), "%", sep = "")
}
@
\begin{figure}[!htb]
\caption{What mode of transportation would you use to and from the dorm?\newline
\scriptsize{\newline
Space for description.}}
\vspace{-20pt}
<<echo=FALSE,cache=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
#<<mygraphTransportation, cache=FALSE, echo=FALSE, messages=FALSE, warnings=FALSE, results="asis", fig.lp="fig:", fig.cap = ''>>=
#print(formatedagetable)
plot <- ggplot(Transportationnewdata, aes(x = factor(1), fill=Transportation)) + geom_bar(width = 0.6) + coord_polar(theta="y") + xlab('') + ylab('') + labs(fill='Response')
plot <- plot + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"))
plot + theme(panel.margin=unit(0,"lines"),axis.ticks=theme_blank(),axis.text.y=theme_blank())
#plot + theme(plot.margin= unit(c(0, 0, 0, 0), "cm"))
rm(plot)
@
\end{figure}

\tikzset{ 
    table/.style={
        matrix of nodes,
        row sep=-\pgflinewidth,
        column sep=-\pgflinewidth,
        nodes={
	rectangle,
	draw=black,
 	align=center,
	anchor=north west,
 %     minimum height=#1,
 %     text width=#1,
      inner sep=8pt
        },
%        text depth=2.5ex,
%        text height=0ex,
        nodes in empty cells,
%%
        every even row/.style={
            nodes={fill=gray!20}
        },
        column 1/.style={
            nodes={text width=9.5em,font=\bfseries}
        },
        column 2/.style={
            nodes={text width=8em,font=\bfseries}
        },
        column 3/.style={
            nodes={text width=8em,font=\bfseries}
        },
        row 1/.style={
            nodes={
                fill=black,
                text=white,
                font=\bfseries,
		minimum height=8.3ex
            }
        },
        row 2/.style={
            nodes={
                text=black,
                font=\bfseries,
minimum height=5.5ex
            }
        },
        row 3/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 4/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 5/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
        row 6/.style={
            nodes={
                text=black,
                font=\bfseries,
 minimum height=5.5ex
            }
        },
    }
}

\begin{table}[!htb]
\caption{Mode of transportation}
%\vspace{-20pt}
\begin{tikzpicture}\matrix (first) [table]
{
Age & Number of Respondents & Percent \%\\ 
\Sexpr{rownames(Transportationnewtable)[1]} & \Sexpr{Transportationnewtable[[1]][[1]]} &  \Sexpr{Transportationnewtable[[2]][[1]]}\% \\ 
\Sexpr{rownames(Transportationnewtable)[2]} & \Sexpr{Transportationnewtable[[1]][[2]]} &  \Sexpr{Transportationnewtable[[2]][[2]]}\% \\ 
\Sexpr{rownames(Transportationnewtable)[3]} & \Sexpr{Transportationnewtable[[1]][[3]]} &  \Sexpr{Transportationnewtable[[2]][[3]]}\% \\  
\Sexpr{rownames(Transportationnewtable)[4]} & \Sexpr{Transportationnewtable[[1]][[4]]} &  \Sexpr{Transportationnewtable[[2]][[4]]}\% \\  
%\Sexpr{rownames(Transportationnewtable)[5]} & \Sexpr{Transportationnewtable[[1]][[5]]} &  \Sexpr{Transportationnewtable[[2]][[5]]}\% \\  
};
\normalsize
\end{tikzpicture}
\end{table}

\textit{* - \Sexpr{trabsportationothercount} of respondents or \Sexpr{sprintf("%.1f",trabsportationotherpercent*100)} percent indicated other mode of transportation. Theose open-ended responses are discussed separately.}

% 18. If a graduate student residence hall is added to Texas Tech’s campus, what suggestions would you give building planners?

\section{Q18. If a graduate student residence hall is added to Texas Tech’s campus, what suggestions would you give building planners?}

\chapter{Summary and Recommendations}
\section{Summary}
Placeholder for the summary or results
\section{Limitations}
Placeholder for the discussion of survey limitations, particularly some of the more "biased" questions.
\section{Recommendations}
Placeholder for the discussion of recommendatiosn for the future.
{\huge Japanese Yen as a Macro Opportunity}
\newline
{\large ME}
\newline
{\large March 13, 2013}
\newline
\newline
\section{Opportunities by Time Scale}
We subdivide market opportunities into three time-scale categories--short-term, cyclical, and secular.  The -------- philosophy is designed to focus on macro secular opportunities.   -------- ignores short-term and only pursues cyclical in the absence of or as a supplement to secular.  Macro or secular trades require patience and persistence.  For this reason, these macro trades get missed by more mainstream and popular investment approaches.  These opportunites are rare and infrequent but lucrative.  I often say that one of the best gauges of the quality of a macro trade is how big a book I can write.  The bigger the book the more the evidence I have and the more time I have had to write.  This is certainly far different from the quick get-rich schemes that dominate the media and get popularized by market lore.
\section{Japanese Yen (\textyen) as an Example of Macro Opportunity}
The Japanese Yen (\textyen) provides a very instructive view of a secular macro opportunity.  We certainly don't want to upset the fickle and vindictive market gods, but I would like to use this as a good example of how we approach these opportunities.



\noindent
The Japanese \textyen \hspace{1pt} strengthened by 370\% versus the US\$ from 1970 to 2009, but just because something goes up a lot over a long time does not mean it will necesarily come down.
\begin{figure}[!htb]
\caption{Japanese \textyen \hspace{1pt} / US\$ Since 1970\newline
\scriptsize{\newline
While not specifically relevant to this chart, I include the shaded areas and dots to put the recent holding periods in the context of a much larger process. The light gray shaded areas represent holding periods for --------.  Green dots are entry dates, and red dots are exit dates.\newline\newline\newline source: Federal Reserve Economic Data (FRED) from the Federal Reserve Bank of St. Louis}}
\vspace{-20pt}
%<<echo=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
\end{figure}
\vspace{-10pt}

\section{Catalysts for Reversal}
We must explore the underlying conditions for the 40 year trend, and then think through the potential catalysts for a reversal.  Often, these initial catalysts are short-term mean reversion and fundamental overvaluation generated by the last wave of fickle buyers who buy just chasing momentum.  During this last stage, the market prefers to extrapolate the trend ignoring slow moving barely perceptible environmental shifts.  Throughout market history, we find numerous examples where the market misses these shifts.



\noindent
When the supporting conditions for the move have eroded while the market has overvalued/undervalued the instrument on both an absolute and relative basis, we begin to closely monitor the price for moves in the direction opposite to the trend.  A secular move of this magnitude takes a very long time to turn.  These short term moves are generally met with market disbelief or apathy as sellers have grown weary and reluctant.  However, the combination of overvaluation and erosion of supportive conditions renders an opportunity ripe for positive or self-fulfilling feedback.


\section{Managing the Entry}
Since perfect timing of the top/bottom is impossible, we very systematically begin to trade.  The last thing we want to happen is to lose too much money or lose confidence by the time the move finally develops, so we are very patient and persistent.  We began this process in Fall 2010 selling the Japanese \textyen \hspace{1pt} as shown in the chart (reversed to US\$/\textyen) below, so up is good.  Each time we shorted (shaded areas in the chart) we would accept very little risk and exit quickly if the price moved aversely.

\begin{figure}
\caption{US\$ / Japanese \textyen \hspace{1pt} Since Dec. 2009\newline
\scriptsize{\newline
Light gray shaded areas represent holding periods for --------.  Green dots are entry dates, and red dots are exit dates.\newline\newline\newline source: Federal Reserve Economic Data (FRED) from the Federal Reserve Bank of St. Louis}}
\vspace{-20pt}
%<<echo=FALSE,eval=TRUE,out.width='1.00\\linewidth',fig.align='left',warning=FALSE,message=FALSE,error=FALSE>>=
\end{figure}
\vspace{-10pt}


\noindent
Remember for positive feedback to engage the first thing that needs to happen is a price move in the appropriate direction.  Our current short is actually the 6th time we have shorted the \textyen \hspace{1pt}.  Now that the first step in the positive feedback loop has occurred, we become much more stubborn and insist on fully benefitting from a much more substantial and long-term process.  If we refer back to the long-term chart, the recent move is barely perceptible.


\section{Once In a Lifetime}
During an investing career of 10-30 years, macro opportunities might only occur 1-5 times.  Unless an investor specifically focuses on studying these rare events, missing these "once-in-a-lifetime" opportunities is common.  Fortunately, we have centuries of market history that can instruct us to discover, pursue, and hopefully profit from these unique occurrences.
\begin{quote}
After spending many years in Wall Street and after making and losing millions of dollars I want to tell you this: It never was my thinking that made big money for me. It was always my sitting.  Got that?  My sitting tight!  It is no trick at all to be right on the market...Men who can both be right and sit tight are uncommon.  I found it one of the hardest things to learn. \par\emph{Reminiscences of a Stock Operator\newline by Edwin Lefevre}
\end{quote}

\begin{center}
\line(1,0){450pt}
\end{center}
\small\textbf{Past performance does not guarantee future results.  This should not be considered investment advice.}

\end{document}